//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Idiomas.SecretarioAcademico.PlanDeEstudio {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Idiomas.SecretarioAcademico.PlanDeEstudio.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar correlativas a una materia.
        /// </summary>
        internal static string btnAsignarCorrelativas {
            get {
                return ResourceManager.GetString("btnAsignarCorrelativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar correlativas.
        /// </summary>
        internal static string btnConsultarCorrelativas {
            get {
                return ResourceManager.GetString("btnConsultarCorrelativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Plan de Estudio.
        /// </summary>
        internal static string btnGuardarPE {
            get {
                return ResourceManager.GetString("btnGuardarPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Materia.
        /// </summary>
        internal static string button4 {
            get {
                return ResourceManager.GetString("button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar Materia.
        /// </summary>
        internal static string button5 {
            get {
                return ResourceManager.GetString("button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        internal static string lblAño {
            get {
                return ResourceManager.GetString("lblAño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga Horaria.
        /// </summary>
        internal static string lblCargaHoraria {
            get {
                return ResourceManager.GetString("lblCargaHoraria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrera.
        /// </summary>
        internal static string lblCarrera {
            get {
                return ResourceManager.GetString("lblCarrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materia (con correlatividad).
        /// </summary>
        internal static string lblMatConCorr {
            get {
                return ResourceManager.GetString("lblMatConCorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Plan.
        /// </summary>
        internal static string lblNombrePlan {
            get {
                return ResourceManager.GetString("lblNombrePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Materia.
        /// </summary>
        internal static string lblNumeroMateria {
            get {
                return ResourceManager.GetString("lblNumeroMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obligatoriedad.
        /// </summary>
        internal static string lblObligatoriedad {
            get {
                return ResourceManager.GetString("lblObligatoriedad", resourceCulture);
            }
        }
    }
}
